import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Essential Linen Shirt",
    price: 2699,
    category: "tops",
    colors: ["white", "cream", "black", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-linen-shirt-minimal-luxury-fashion.jpg",
    images: [
      "/white-linen-shirt-minimal-luxury-fashion.jpg",
      "/linen-shirt-cream-detail-fabric-close-up.jpg",
      "/linen-shirt-flat-lay-styling-on-model.jpg",
    ],
    description: "Timeless linen shirt crafted from premium European linen. Perfect for layering or wearing solo.",
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Tailored Trousers",
    price: 3299,
    category: "bottoms",
    colors: ["black", "grey", "navy", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: [
      "/black-tailored-trousers-minimal-fashion-luxury.jpg",
      "/trousers-detail-stitching-quality-close-up.jpg",
      "/trousers-worn-on-model-styling-outfit.jpg",
    ],
    description: "Perfectly tailored trousers with a clean silhouette. Made from sustainable Italian wool blend.",
    rating: 4.9,
    reviews: 98,
  },
  {
    id: "3",
    name: "Oversized Blazer",
    price: 4599,
    category: "outerwear",
    colors: ["black", "cream", "chocolate", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-oversized-blazer-modern-luxury-fashion.jpg",
    images: [
      "/cream-oversized-blazer-modern-luxury-fashion.jpg",
      "/blazer-detail-lapel-stitching-close-up.jpg",
      "/blazer-worn-on-model-styling-professional.jpg",
    ],
    description: "Modern oversized blazer featuring contemporary tailoring and luxe fabric finishes.",
    rating: 4.7,
    reviews: 87,
  },
  {
    id: "4",
    name: "Minimal White T-Shirt",
    price: 2799,
    category: "tops",
    colors: ["white", "black", "grey", "beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
    images: [
      "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
      "/t-shirt-fabric-close-up-texture-quality.jpg",
      "/t-shirt-worn-casual-model-styling-outfit.jpg",
    ],
    description: "Premium cotton t-shirt with perfect fit and durability. A staple for any wardrobe.",
    rating: 4.6,
    reviews: 156,
  },
  {
    id: "5",
    name: "Wide-Leg Denim",
    price: 3499,
    category: "bottoms",
    colors: ["indigo", "black", "light-blue", "white"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg",
    images: [
      "/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg",
      "/denim-detail-stitching-quality-close-up.jpg",
      "/denim-worn-on-model-styling-casual-outfit.jpg",
    ],
    description: "Contemporary wide-leg denim in premium Japanese fabric. Sustainably sourced and crafted.",
    rating: 4.8,
    reviews: 112,
  },
  {
    id: "6",
    name: "Silk Slip Dress",
    price: 3999,
    category: "dresses",
    colors: ["champagne", "black", "ivory", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: [
      "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
      "/silk-slip-dress-detail-fabric-luxury-close-up.jpg",
      "/silk-slip-dress-worn-elegant-styling-on-model.jpg",
    ],
    description: "Luxe silk slip dress with delicate straps. Versatile day to night piece.",
    rating: 4.9,
    reviews: 143,
  },
  {
    id: "7",
    name: "Wool Knit Sweater",
    price: 3199,
    category: "tops",
    colors: ["cream", "grey", "black", "navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
    images: [
      "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
      "/wool-sweater-detail-knit-texture-close-up-quality.jpg",
      "/wool-sweater-worn-on-model-styling-casual-outfit.jpg",
    ],
    description: "Premium merino wool sweater with timeless design. Warm, breathable, and sustainable.",
    rating: 4.7,
    reviews: 95,
  },
  {
    id: "8",
    name: "Leather Loafers",
    price: 5499,
    category: "shoes",
    colors: ["black", "brown", "camel", "white"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: [
      "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
      "/leather-loafers-detail-sole-stitching-close-up-quality.jpg",
      "/leather-loafers-worn-on-model-styling-professional.jpg",
    ],
    description: "Classic leather loafers crafted from premium Italian leather. Timeless and versatile.",
    rating: 4.8,
    reviews: 78,
  },
  {
    id: "9",
    name: "Classic Button-Down Shirt",
    price: 2899,
    category: "tops",
    colors: ["white", "navy", "black", "grey"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-linen-shirt-minimal-luxury-fashion.jpg",
    images: ["/white-linen-shirt-minimal-luxury-fashion.jpg", "/linen-shirt-cream-detail-fabric-close-up.jpg", "/linen-shirt-flat-lay-styling-on-model.jpg"],
    description: "Versatile button-down shirt with crisp finish. Perfect for professional and casual settings.",
    rating: 4.7,
    reviews: 203,
  },
  {
    id: "10",
    name: "Ribbed Knit Tank Top",
    price: 2699,
    category: "tops",
    colors: ["black", "white", "beige", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
    images: ["/white-luxury-t-shirt-minimal-premium-cotton.jpg", "/t-shirt-fabric-close-up-texture-quality.jpg", "/t-shirt-worn-casual-model-styling-outfit.jpg"],
    description: "Soft ribbed tank top in premium cotton blend. Ideal for layering or solo wear.",
    rating: 4.6,
    reviews: 167,
  },
  {
    id: "11",
    name: "Oversized Cotton Sweatshirt",
    price: 3299,
    category: "tops",
    colors: ["grey", "black", "cream", "navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
    images: ["/cream-wool-knit-sweater-luxury-premium-minimal.jpg", "/wool-sweater-detail-knit-texture-close-up-quality.jpg", "/wool-sweater-worn-on-model-styling-casual-outfit.jpg"],
    description: "Cozy oversized sweatshirt with relaxed fit. Made from organic cotton for ultimate comfort.",
    rating: 4.8,
    reviews: 189,
  },
  {
    id: "12",
    name: "Silk Camisole",
    price: 3499,
    category: "tops",
    colors: ["black", "champagne", "ivory", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Elegant silk camisole with adjustable straps. Luxurious fabric that feels as good as it looks.",
    rating: 4.9,
    reviews: 142,
  },
  {
    id: "13",
    name: "Long-Sleeve Striped Shirt",
    price: 2999,
    category: "tops",
    colors: ["white", "navy", "black", "beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-linen-shirt-minimal.jpg",
    images: ["/white-linen-shirt-minimal.jpg", "/linen-shirt-cream-detail.jpg", "/linen-shirt-flat-lay.jpg"],
    description: "Classic striped shirt with French cuffs. Timeless design with modern tailoring.",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "14",
    name: "Cropped Cashmere Sweater",
    price: 4899,
    category: "tops",
    colors: ["cream", "black", "navy", "grey"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
    images: ["/cream-wool-knit-sweater-luxury-premium-minimal.jpg", "/wool-sweater-detail-knit-texture-close-up-quality.jpg", "/wool-sweater-worn-on-model-styling-casual-outfit.jpg"],
    description: "Luxurious cropped cashmere sweater. Ultra-soft and warm, perfect for transitional weather.",
    rating: 4.9,
    reviews: 128,
  },
  {
    id: "15",
    name: "Mock Neck Long Sleeve Top",
    price: 2799,
    category: "tops",
    colors: ["black", "white", "grey", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-t-shirt-minimal-luxury.jpg",
    images: ["/white-t-shirt-minimal-luxury.jpg", "/t-shirt-fabric-close-up.jpg", "/t-shirt-worn-casual.jpg"],
    description: "Sleek mock neck top in stretch fabric. Versatile piece that transitions seamlessly.",
    rating: 4.6,
    reviews: 198,
  },
  {
    id: "16",
    name: "Oversized White Shirt",
    price: 2999,
    category: "tops",
    colors: ["white", "cream", "black", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-linen-shirt-minimal-luxury-fashion.jpg",
    images: ["/white-linen-shirt-minimal-luxury-fashion.jpg", "/linen-shirt-cream-detail-fabric-close-up.jpg", "/linen-shirt-flat-lay-styling-on-model.jpg"],
    description: "Relaxed fit white shirt with clean lines. Effortlessly chic and endlessly versatile.",
    rating: 4.8,
    reviews: 174,
  },
  {
    id: "17",
    name: "V-Neck Cashmere Blend Tee",
    price: 3199,
    category: "tops",
    colors: ["white", "black", "navy", "beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
    images: ["/white-luxury-t-shirt-minimal-premium-cotton.jpg", "/t-shirt-fabric-close-up-texture-quality.jpg", "/t-shirt-worn-casual-model-styling-outfit.jpg"],
    description: "Premium cashmere blend t-shirt with refined v-neck. Elevated basics done right.",
    rating: 4.7,
    reviews: 145,
  },
  {
    id: "18",
    name: "Sleeveless Blouse",
    price: 2899,
    category: "tops",
    colors: ["white", "black", "champagne", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-linen-shirt-minimal-luxury-fashion.jpg",
    images: ["/white-linen-shirt-minimal-luxury-fashion.jpg", "/linen-shirt-cream-detail-fabric-close-up.jpg", "/linen-shirt-flat-lay-styling-on-model.jpg"],
    description: "Elegant sleeveless blouse with draping details. Perfect for layering under blazers.",
    rating: 4.8,
    reviews: 162,
  },
  {
    id: "19",
    name: "Ribbed High-Neck Top",
    price: 2699,
    category: "tops",
    colors: ["black", "white", "navy", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
    images: ["/white-luxury-t-shirt-minimal-premium-cotton.jpg", "/t-shirt-fabric-close-up-texture-quality.jpg", "/t-shirt-worn-casual-model-styling-outfit.jpg"],
    description: "Modern ribbed top with high neckline. Sleek silhouette for contemporary styling.",
    rating: 4.6,
    reviews: 211,
  },
  {
    id: "20",
    name: "Oversized Cardigan",
    price: 4299,
    category: "tops",
    colors: ["cream", "black", "grey", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
    images: ["/cream-wool-knit-sweater-luxury-premium-minimal.jpg", "/wool-sweater-detail-knit-texture-close-up-quality.jpg", "/wool-sweater-worn-on-model-styling-casual-outfit.jpg"],
    description: "Chunky knit oversized cardigan. Cozy layering piece for chilly days.",
    rating: 4.7,
    reviews: 137,
  },
  {
    id: "21",
    name: "Turtleneck Sweater",
    price: 3599,
    category: "tops",
    colors: ["black", "cream", "navy", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
    images: ["/cream-wool-knit-sweater-luxury-premium-minimal.jpg", "/wool-sweater-detail-knit-texture-close-up-quality.jpg", "/wool-sweater-worn-on-model-styling-casual-outfit.jpg"],
    description: "Classic turtleneck in premium merino wool. Timeless elegance meets modern comfort.",
    rating: 4.8,
    reviews: 153,
  },
  {
    id: "22",
    name: "Wide-Leg Trousers",
    price: 3799,
    category: "bottoms",
    colors: ["black", "navy", "grey", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: ["/black-tailored-trousers-minimal-fashion-luxury.jpg", "/trousers-detail-stitching-quality-close-up.jpg", "/trousers-worn-on-model-styling-outfit.jpg"],
    description: "Elegant wide-leg trousers with flowing silhouette. Comfortable and sophisticated.",
    rating: 4.9,
    reviews: 119,
  },
  {
    id: "23",
    name: "Straight Leg Denim Jeans",
    price: 3399,
    category: "bottoms",
    colors: ["indigo", "black", "light-blue", "white"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg",
    images: ["/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg", "/denim-detail-stitching-quality-close-up.jpg", "/denim-worn-on-model-styling-casual-outfit.jpg"],
    description: "Classic straight leg jeans in premium denim. Perfect fit and timeless style.",
    rating: 4.7,
    reviews: 234,
  },
  {
    id: "24",
    name: "Pleated Midi Skirt",
    price: 3199,
    category: "bottoms",
    colors: ["black", "navy", "taupe", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: ["/black-tailored-trousers-minimal-fashion-luxury.jpg", "/trousers-detail-stitching-quality-close-up.jpg", "/trousers-worn-on-model-styling-outfit.jpg"],
    description: "Elegant pleated midi skirt in flowing fabric. Versatile and feminine.",
    rating: 4.8,
    reviews: 167,
  },
  {
    id: "25",
    name: "High-Waisted Cropped Trousers",
    price: 3299,
    category: "bottoms",
    colors: ["black", "navy", "cream", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/tailored-black-trousers-minimal.jpg",
    images: ["/tailored-black-trousers-minimal.jpg", "/trousers-detail-stitching.jpg", "/trousers-worn-styling.jpg"],
    description: "Modern cropped trousers with high waist. Perfect length for any season.",
    rating: 4.7,
    reviews: 148,
  },
  {
    id: "26",
    name: "Cargo Pants",
    price: 3599,
    category: "bottoms",
    colors: ["black", "navy", "taupe", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: ["/black-tailored-trousers-minimal-fashion-luxury.jpg", "/trousers-detail-stitching-quality-close-up.jpg", "/trousers-worn-on-model-styling-outfit.jpg"],
    description: "Functional cargo pants with utility pockets. Urban style meets practicality.",
    rating: 4.6,
    reviews: 176,
  },
  {
    id: "27",
    name: "Wrap Midi Skirt",
    price: 2999,
    category: "bottoms",
    colors: ["black", "navy", "sage", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: ["/black-tailored-trousers-minimal-fashion-luxury.jpg", "/trousers-detail-stitching-quality-close-up.jpg", "/trousers-worn-on-model-styling-outfit.jpg"],
    description: "Flattering wrap midi skirt with adjustable fit. Effortlessly chic design.",
    rating: 4.8,
    reviews: 142,
  },
  {
    id: "28",
    name: "Cropped Wide-Leg Pants",
    price: 3499,
    category: "bottoms",
    colors: ["black", "navy", "cream", "grey"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/wide-leg-denim-indigo.jpg",
    images: ["/wide-leg-denim-indigo.jpg", "/denim-detail-stitching.jpg", "/denim-worn-styling.jpg"],
    description: "Contemporary cropped wide-leg pants. Comfortable and stylish.",
    rating: 4.7,
    reviews: 159,
  },
  {
    id: "29",
    name: "Midi A-Line Skirt",
    price: 2899,
    category: "bottoms",
    colors: ["black", "navy", "taupe", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: ["/black-tailored-trousers-minimal-fashion-luxury.jpg", "/trousers-detail-stitching-quality-close-up.jpg", "/trousers-worn-on-model-styling-outfit.jpg"],
    description: "Classic A-line midi skirt in premium fabric. Timeless elegance.",
    rating: 4.8,
    reviews: 134,
  },
  {
    id: "30",
    name: "Maxi Midi Dress",
    price: 4199,
    category: "dresses",
    colors: ["black", "navy", "sage", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Flowing maxi dress with elegant draping. Perfect for special occasions.",
    rating: 4.9,
    reviews: 108,
  },
  {
    id: "31",
    name: "Wrap Midi Dress",
    price: 3799,
    category: "dresses",
    colors: ["black", "navy", "champagne", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Flattering wrap dress with adjustable fit. Versatile day to night piece.",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: "32",
    name: "Button-Down Shirt Dress",
    price: 3899,
    category: "dresses",
    colors: ["white", "black", "navy", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Classic shirt dress with modern tailoring. Effortlessly sophisticated.",
    rating: 4.7,
    reviews: 187,
  },
  {
    id: "33",
    name: "Midi A-Line Dress",
    price: 3699,
    category: "dresses",
    colors: ["black", "navy", "taupe", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Elegant A-line midi dress with clean lines. Timeless and refined.",
    rating: 4.8,
    reviews: 143,
  },
  {
    id: "34",
    name: "Sleeveless Shift Dress",
    price: 3499,
    category: "dresses",
    colors: ["black", "navy", "cream", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Modern shift dress with clean silhouette. Perfect for layering or wearing solo.",
    rating: 4.7,
    reviews: 172,
  },
  {
    id: "35",
    name: "Tiered Maxi Dress",
    price: 4399,
    category: "dresses",
    colors: ["black", "navy", "sage", "champagne"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Romantic tiered maxi dress with flowing layers. Feminine and elegant.",
    rating: 4.9,
    reviews: 127,
  },
  {
    id: "36",
    name: "Turtleneck Midi Dress",
    price: 3999,
    category: "dresses",
    colors: ["black", "navy", "taupe", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: ["/champagne-silk-slip-dress-luxury-minimal-elegant.jpg", "/silk-slip-dress-detail-fabric-luxury-close-up.jpg", "/silk-slip-dress-worn-elegant-styling-on-model.jpg"],
    description: "Sophisticated turtleneck midi dress. Modern elegance with timeless appeal.",
    rating: 4.8,
    reviews: 151,
  },
  {
    id: "37",
    name: "Trench Coat",
    price: 5999,
    category: "outerwear",
    colors: ["black", "navy", "cream", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-oversized-blazer-modern-luxury-fashion.jpg",
    images: ["/cream-oversized-blazer-modern-luxury-fashion.jpg", "/blazer-detail-lapel-stitching-close-up.jpg", "/blazer-worn-on-model-styling-professional.jpg"],
    description: "Classic trench coat with modern updates. Waterproof and timelessly elegant.",
    rating: 4.9,
    reviews: 112,
  },
  {
    id: "38",
    name: "Wool Blend Coat",
    price: 6499,
    category: "outerwear",
    colors: ["black", "navy", "charcoal", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/oversized-blazer-cream-minimal.jpg",
    images: ["/oversized-blazer-cream-minimal.jpg", "/blazer-detail-lapel.jpg", "/blazer-worn-styling.jpg"],
    description: "Luxurious wool blend coat with structured silhouette. Perfect for cold weather.",
    rating: 4.8,
    reviews: 98,
  },
  {
    id: "39",
    name: "Denim Jacket",
    price: 3899,
    category: "outerwear",
    colors: ["indigo", "black", "light-blue", "white"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg",
    images: ["/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg", "/denim-detail-stitching-quality-close-up.jpg", "/denim-worn-on-model-styling-casual-outfit.jpg"],
    description: "Classic denim jacket in premium fabric. Versatile layering piece.",
    rating: 4.7,
    reviews: 203,
  },
  {
    id: "40",
    name: "Quilted Puffer Jacket",
    price: 5299,
    category: "outerwear",
    colors: ["black", "navy", "charcoal", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-oversized-blazer-modern-luxury-fashion.jpg",
    images: ["/cream-oversized-blazer-modern-luxury-fashion.jpg", "/blazer-detail-lapel-stitching-close-up.jpg", "/blazer-worn-on-model-styling-professional.jpg"],
    description: "Warm and lightweight puffer jacket. Perfect for winter adventures.",
    rating: 4.8,
    reviews: 167,
  },
  {
    id: "41",
    name: "Leather Moto Jacket",
    price: 7499,
    category: "outerwear",
    colors: ["black", "brown", "charcoal", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-oversized-blazer-modern-luxury-fashion.jpg",
    images: ["/cream-oversized-blazer-modern-luxury-fashion.jpg", "/blazer-detail-lapel-stitching-close-up.jpg", "/blazer-worn-on-model-styling-professional.jpg"],
    description: "Edgy leather moto jacket with quality hardware. Timeless rock-and-roll style.",
    rating: 4.9,
    reviews: 134,
  },
  {
    id: "42",
    name: "Wool Wrap Coat",
    price: 5999,
    category: "outerwear",
    colors: ["black", "navy", "charcoal", "cream"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/oversized-blazer-cream-minimal.jpg",
    images: ["/oversized-blazer-cream-minimal.jpg", "/blazer-detail-lapel.jpg", "/blazer-worn-styling.jpg"],
    description: "Elegant wrap coat in premium wool. Sophisticated and warm.",
    rating: 4.8,
    reviews: 119,
  },
  {
    id: "43",
    name: "Shackets & Overshirts",
    price: 4499,
    category: "outerwear",
    colors: ["black", "navy", "cream", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-oversized-blazer-modern-luxury-fashion.jpg",
    images: ["/cream-oversized-blazer-modern-luxury-fashion.jpg", "/blazer-detail-lapel-stitching-close-up.jpg", "/blazer-worn-on-model-styling-professional.jpg"],
    description: "Versatile shacket in soft flannel fabric. Perfect transitional layering piece.",
    rating: 4.7,
    reviews: 178,
  },
  {
    id: "44",
    name: "Canvas Sneakers",
    price: 3799,
    category: "shoes",
    colors: ["white", "black", "navy", "beige"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Classic canvas sneakers with minimalist design. Comfortable and versatile.",
    rating: 4.7,
    reviews: 289,
  },
  {
    id: "45",
    name: "Ankle Boots",
    price: 5999,
    category: "shoes",
    colors: ["black", "brown", "taupe", "charcoal"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Stylish ankle boots with low heel. Perfect for everyday wear.",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: "46",
    name: "Platform Sandals",
    price: 4299,
    category: "shoes",
    colors: ["black", "brown", "beige", "taupe"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Elegant platform sandals with adjustable straps. Comfortable height and style.",
    rating: 4.7,
    reviews: 143,
  },
  {
    id: "47",
    name: "Slip-On Mules",
    price: 3599,
    category: "shoes",
    colors: ["black", "brown", "beige", "taupe"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Effortless slip-on mules in premium leather. Easy elegance for any occasion.",
    rating: 4.8,
    reviews: 167,
  },
  {
    id: "48",
    name: "Oxford Shoes",
    price: 5499,
    category: "shoes",
    colors: ["black", "brown", "taupe", "charcoal"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Classic Oxford shoes with timeless design. Perfect for professional settings.",
    rating: 4.9,
    reviews: 124,
  },
  {
    id: "49",
    name: "Leather Ballet Flats",
    price: 3999,
    category: "shoes",
    colors: ["black", "brown", "beige", "taupe"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Comfortable ballet flats in supple leather. Effortlessly chic and versatile.",
    rating: 4.7,
    reviews: 198,
  },
  {
    id: "50",
    name: "High-Top Sneakers",
    price: 4799,
    category: "shoes",
    colors: ["white", "black", "navy", "grey"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: ["/black-leather-loafers-luxury-minimal-shoes-quality.jpg", "/leather-loafers-detail-sole-stitching-close-up-quality.jpg", "/leather-loafers-worn-on-model-styling-professional.jpg"],
    description: "Sporty high-top sneakers with premium construction. Style meets comfort.",
    rating: 4.8,
    reviews: 175,
  },
]

export const categories = [
  { id: "all", name: "All Products", count: 50 },
  { id: "tops", name: "Tops", count: 15 },
  { id: "bottoms", name: "Bottoms", count: 10 },
  { id: "dresses", name: "Dresses", count: 8 },
  { id: "outerwear", name: "Outerwear", count: 8 },
  { id: "shoes", name: "Shoes", count: 9 },
]

export const priceRanges = [
  { id: "2500-3000", label: "₹2500 - ₹3000", min: 2500, max: 3000 },
  { id: "3000-4000", label: "₹3000 - ₹4000", min: 3000, max: 4000 },
  { id: "4000-5000", label: "₹4000 - ₹5000", min: 4000, max: 5000 },
  { id: "5000+", label: "₹5000+", min: 5000, max: Number.POSITIVE_INFINITY },
]

export const colors = [
  { id: "white", name: "White", hex: "#FFFFFF" },
  { id: "black", name: "Black", hex: "#000000" },
  { id: "cream", name: "Cream", hex: "#F5F3F0" },
  { id: "grey", name: "Grey", hex: "#8B8B8B" },
  { id: "navy", name: "Navy", hex: "#2C3E50" },
  { id: "sage", name: "Sage", hex: "#9CAF88" },
  { id: "taupe", name: "Taupe", hex: "#B3A89D" },
  { id: "charcoal", name: "Charcoal", hex: "#36454F" },
]
