import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Essential Linen Shirt",
    price: 2699,
    category: "tops",
    colors: ["white", "cream", "black", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-linen-shirt-minimal-luxury-fashion.jpg",
    images: [
      "/white-linen-shirt-minimal-luxury-fashion.jpg",
      "/linen-shirt-cream-detail-fabric-close-up.jpg",
      "/linen-shirt-flat-lay-styling-on-model.jpg",
    ],
    description: "Timeless linen shirt crafted from premium European linen. Perfect for layering or wearing solo.",
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Tailored Trousers",
    price: 3299,
    category: "bottoms",
    colors: ["black", "grey", "navy", "taupe"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/black-tailored-trousers-minimal-fashion-luxury.jpg",
    images: [
      "/black-tailored-trousers-minimal-fashion-luxury.jpg",
      "/trousers-detail-stitching-quality-close-up.jpg",
      "/trousers-worn-on-model-styling-outfit.jpg",
    ],
    description: "Perfectly tailored trousers with a clean silhouette. Made from sustainable Italian wool blend.",
    rating: 4.9,
    reviews: 98,
  },
  {
    id: "3",
    name: "Oversized Blazer",
    price: 4599,
    category: "outerwear",
    colors: ["black", "cream", "chocolate", "charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-oversized-blazer-modern-luxury-fashion.jpg",
    images: [
      "/cream-oversized-blazer-modern-luxury-fashion.jpg",
      "/blazer-detail-lapel-stitching-close-up.jpg",
      "/blazer-worn-on-model-styling-professional.jpg",
    ],
    description: "Modern oversized blazer featuring contemporary tailoring and luxe fabric finishes.",
    rating: 4.7,
    reviews: 87,
  },
  {
    id: "4",
    name: "Minimal White T-Shirt",
    price: 2799,
    category: "tops",
    colors: ["white", "black", "grey", "beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
    images: [
      "/white-luxury-t-shirt-minimal-premium-cotton.jpg",
      "/t-shirt-fabric-close-up-texture-quality.jpg",
      "/t-shirt-worn-casual-model-styling-outfit.jpg",
    ],
    description: "Premium cotton t-shirt with perfect fit and durability. A staple for any wardrobe.",
    rating: 4.6,
    reviews: 156,
  },
  {
    id: "5",
    name: "Wide-Leg Denim",
    price: 3499,
    category: "bottoms",
    colors: ["indigo", "black", "light-blue", "white"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg",
    images: [
      "/indigo-wide-leg-denim-luxury-premium-japanese-fabr.jpg",
      "/denim-detail-stitching-quality-close-up.jpg",
      "/denim-worn-on-model-styling-casual-outfit.jpg",
    ],
    description: "Contemporary wide-leg denim in premium Japanese fabric. Sustainably sourced and crafted.",
    rating: 4.8,
    reviews: 112,
  },
  {
    id: "6",
    name: "Silk Slip Dress",
    price: 3999,
    category: "dresses",
    colors: ["champagne", "black", "ivory", "sage"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
    images: [
      "/champagne-silk-slip-dress-luxury-minimal-elegant.jpg",
      "/silk-slip-dress-detail-fabric-luxury-close-up.jpg",
      "/silk-slip-dress-worn-elegant-styling-on-model.jpg",
    ],
    description: "Luxe silk slip dress with delicate straps. Versatile day to night piece.",
    rating: 4.9,
    reviews: 143,
  },
  {
    id: "7",
    name: "Wool Knit Sweater",
    price: 3199,
    category: "tops",
    colors: ["cream", "grey", "black", "navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
    images: [
      "/cream-wool-knit-sweater-luxury-premium-minimal.jpg",
      "/wool-sweater-detail-knit-texture-close-up-quality.jpg",
      "/wool-sweater-worn-on-model-styling-casual-outfit.jpg",
    ],
    description: "Premium merino wool sweater with timeless design. Warm, breathable, and sustainable.",
    rating: 4.7,
    reviews: 95,
  },
  {
    id: "8",
    name: "Leather Loafers",
    price: 5499,
    category: "shoes",
    colors: ["black", "brown", "camel", "white"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
    image: "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
    images: [
      "/black-leather-loafers-luxury-minimal-shoes-quality.jpg",
      "/leather-loafers-detail-sole-stitching-close-up-quality.jpg",
      "/leather-loafers-worn-on-model-styling-professional.jpg",
    ],
    description: "Classic leather loafers crafted from premium Italian leather. Timeless and versatile.",
    rating: 4.8,
    reviews: 78,
  },
]

export const categories = [
  { id: "all", name: "All Products", count: 8 },
  { id: "tops", name: "Tops", count: 3 },
  { id: "bottoms", name: "Bottoms", count: 2 },
  { id: "dresses", name: "Dresses", count: 1 },
  { id: "outerwear", name: "Outerwear", count: 1 },
  { id: "shoes", name: "Shoes", count: 1 },
]

export const priceRanges = [
  { id: "2500-3000", label: "₹2500 - ₹3000", min: 2500, max: 3000 },
  { id: "3000-4000", label: "₹3000 - ₹4000", min: 3000, max: 4000 },
  { id: "4000-5000", label: "₹4000 - ₹5000", min: 4000, max: 5000 },
  { id: "5000+", label: "₹5000+", min: 5000, max: Number.POSITIVE_INFINITY },
]

export const colors = [
  { id: "white", name: "White", hex: "#FFFFFF" },
  { id: "black", name: "Black", hex: "#000000" },
  { id: "cream", name: "Cream", hex: "#F5F3F0" },
  { id: "grey", name: "Grey", hex: "#8B8B8B" },
  { id: "navy", name: "Navy", hex: "#2C3E50" },
  { id: "sage", name: "Sage", hex: "#9CAF88" },
  { id: "taupe", name: "Taupe", hex: "#B3A89D" },
  { id: "charcoal", name: "Charcoal", hex: "#36454F" },
]
